name: udemy_quizzler_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

#flutter 3.27.3
#dart 3.6.1
environment:
  sdk: ">=3.6.0 <3.7.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  #TODO: Step 1 - Add the rFlutter Alert package as a dependency here and use "Packages get".
  rflutter_alert: ^2.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true